spring:
  main:
    allow-circular-references: true
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
imdb:
  api:
    key:
    urls:
      rankings:
        top250movies: https://imdb-api.com/en/API/Top250Movies/
        top250tvs: https://imdb-api.com/en/API/Top250TVs/
      movies:

jwt:
  secret: